import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
DATABASE_NAME = os.getenv("DATABASE_NAME")
SECRET_KEY = os.getenv("SECRET_KEY")
HOST = os.getenv("HOST")
PORT = os.getenv("PORT")
FRONTEND_URL = os.getenv("FRONTEND_URL")

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES =int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS = os.getenv("REFRESH_TOKEN_EXPIRE_DAYS")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

MAILTRAP_PORT = os.getenv("MAILTRAP_PORT")
SMTP_SERVER = os.getenv("SMTP_SERVER")
MAILTRAP_LOGIN = os.getenv("MAILTRAP_LOGIN")
MAILTRAP_PASSWORD = os.getenv("MAILTRAP_PASSWORD")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
VERIFICATION_CODE_EXPIRE_MINUTES = int(os.getenv("VERIFICATION_CODE_EXPIRE_MINUTES"))

GOOGLE_AUTH_URL = os.getenv("GOOGLE_AUTH_URL")